# Generated by Django 4.2.5 on 2023-10-04 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_orderupdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='city',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='email',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='phone',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='province',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='zip',
            field=models.CharField(max_length=30),
        ),
    ]
