# Generated by Django 4.2.5 on 2023-10-04 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_contact_desc_alter_contact_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderupdate',
            name='city',
        ),
        migrations.RemoveField(
            model_name='orderupdate',
            name='email',
        ),
        migrations.RemoveField(
            model_name='orderupdate',
            name='fname',
        ),
        migrations.RemoveField(
            model_name='orderupdate',
            name='items_json',
        ),
        migrations.RemoveField(
            model_name='orderupdate',
            name='lname',
        ),
        migrations.RemoveField(
            model_name='orderupdate',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='orderupdate',
            name='province',
        ),
        migrations.RemoveField(
            model_name='orderupdate',
            name='zip',
        ),
        migrations.AddField(
            model_name='orderupdate',
            name='order_id',
            field=models.IntegerField(default=''),
        ),
        migrations.AddField(
            model_name='orderupdate',
            name='update_desc',
            field=models.CharField(default='', max_length=300),
        ),
    ]
