# Generated by Django 4.2.5 on 2023-10-04 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_orderupdate_timestam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderupdate',
            name='order_id',
        ),
    ]
