# Generated by Django 4.2.5 on 2023-10-08 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_orderupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderupdate',
            name='order_id',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
